#!/usr/bin/env bash
# Configures IP resolution for localhost and facebook.com in /etc/hosts

sed 's/127.0.0.1/127.0.0.2/g' /etc/hosts | tee /etc/hosts > /dev/null
echo "8.8.8.8 facebook.com" >> /etc/hosts
